language: ruby
dist: bionic

rvm: 2.7.5

services:
  - redis

env:
  global:
    - PATH=/snap/bin:$PATH

cache: bundler

bundler_args: --without development --jobs 3 --retry 3 --deployment

jobs:
  include:
    - stage: "rspec"
      before_install:
        - gem install bundler:1.17.3
      script: bundle exec rspec spec
    - stage: ":ship: it"
      addons:
        snaps:
        - name: docker
          channel: latest/beta
      script: make ship
      if: (branch = master and type = push ) OR commit_message =~ /ship:docker/ OR env(SHIP_DOCKER) = true
