language: ruby
dist: bionic
group: edge

before_install:
  - gem install bundler:2.3.7
rvm: 2.5.8

services:
  - redis

env:
  global:
    - PATH=/snap/bin:$PATH

cache: bundler

bundler_args: --without development --jobs 3 --retry 3 --deployment

jobs:
  include:
    - stage: "rspec"
      script: bundle exec rspec spec
    - stage: ":ship: it"
      script: make ship
      if: (branch = master and type = push ) OR commit_message =~ /ship:docker/ OR env(SHIP_DOCKER) = true
