language: ruby
dist: bionic

rvm: 3.2.2

services:
  - redis

env:
  global:
    - PATH=/snap/bin:$PATH

cache: bundler

before_install:
  - gem update --system 3.4.19 > /dev/null 2>&1

bundler_args: --without development --jobs 3 --retry 3 --deployment

jobs:
  include:
    - stage: "rspec"
      script: bundle exec rspec spec
