#!/bin/bash

set -ev

docker-compose build web;

docker login -u=$QUAY_ROBOT_HANDLE -p=$QUAY_ROBOT_TOKEN quay.io;

docker images;

docker tag travislistener_web quay.io/travisci/travis-listener:$TRAVIS_BRANCH;
docker push quay.io/travisci/travis-listener:$TRAVIS_BRANCH;

if [ ${TRAVIS_BRANCH} = "master" ]; then
  docker tag travislistener_web quay.io/travisci/travis-listener:latest";
  docker push travislistener_web quay.io/travisci/travis-listener:$TRAVIS_BRANCH";
fi

exit 0;
