#!/bin/bash

set -ev

quay_image=quay.io/travisci/travis-build
tag_name=$(echo "$TRAVIS_BRANCH" | sed -e "s/\\//-/g")

docker build -t "${quay_image}:${tag_name}" .

docker login -u=$QUAY_ROBOT_HANDLE -p=$QUAY_ROBOT_TOKEN quay.io;

docker images;

docker tag "${quay_image}" "${quay_image}:${tag_name}";
docker push "${tag_name}:${tag_name}";

docker tag "${quay_image}" "${quay_image}:${TRAVIS_COMMIT:0:7}";
docker push "${quay_image}:${TRAVIS_COMMIT:0:7}";

if [ ${TRAVIS_BRANCH} = "master" ]; then
  docker tag "${quay_image}" "${quay_image}:latest";
  docker push "${quay_image}:latest";
fi

exit 0;
